env:
  # ブラウザで使用するのでbrowserとes2021をONにしておく
  browser: true
  es2021:
    true
    # Vue3で使用するdefinePropsやdefineEmits,defineExposeなどを使用できるようにする
  "vue/setup-compiler-macros": true
extends:
  - "plugin:vue/vue3-recommended"
  - "eslint:recommended"
  - "@vue/typescript/recommended"
  - "prettier"
parserOptions:
  # parser: "@typescript-eslint/parser"
  ecmaVersion: 2021
plugins:
  - vue
  - "@typescript-eslint"
rules: {}
