printWidth: 80
semi: false
singleQuote: false
tabWidth: 2
arrowParens: "always"
endOfLine: "lf"
useTabs: false
quoteProps: "as-needed"
jsxSingleQuote: false
trailingComma: "es5"
bracketSpacing: true
jsxBracketSameLine: false
